<div id="slider">	    
  <div class="wrap">
<div class="slides_container">			    			    			    	
      <div class="entry-slides">
        <div class="entry-embed">
          <iframe src="http://player.vimeo.com/video/33670490?title=0&amp;byline=0&amp;portrait=0" width="400" height="225" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
        </div>
	    <h2 class="entry-title">
          <a href="http://www.jamedy.com/2012/01/14/the-artists/" rel="bookmark" title="Permanent Link to The Artists">The Artists</a>
        </h2><!-- .entry-title -->
        <div class="entry-meta">
          <abbr title="January 14, 2012 at 3:21 pm">January 14, 2012</abbr> &middot; by <a href="http://www.jamedy.com/author/admin/" title="Posts by admin" rel="author">admin</a>
        </div><!-- .entry-meta -->        
        <div class="entry-content">
          <p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam molestie molestie nisl, eu scelerisque turpis tempus at. Nam luctus ultrices imperdiet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse velit orci, pretium ut feugiat nec, lobortis et est. Nullam cursus ultrices tincidunt. Nam gravida sem gravida ipsum dignissim in [&hellip;]</p></p>
          <a href="http://www.jamedy.com/2012/01/14/the-artists/" rel="bookmark" class="read-more">Continue Reading &raquo;</a>
	    </div><!-- .entry-content -->
      </div><!-- #post-155 -->
	  <div class="entry-slides">
      <div class="entry-embed">
        <object style="height: 390px; width: 640px"><param name="movie" value="http://www.youtube.com/v/n9glLfPzehU?version=3&feature=player_detailpage"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><embed src="http://www.youtube.com/v/n9glLfPzehU?version=3&feature=player_detailpage" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="640" height="360"></object>    </div>
	    <h2 class="entry-title">
            <a href="http://www.jamedy.com/2012/01/14/lady-vol-basketball-vs-texas/" rel="bookmark" title="Permanent Link to Lady Vol Basketball vs. Texas">
                Lady Vol Basketball vs. Texas            </a>
        </h2><!-- .entry-title -->
        <div class="entry-meta">
            <abbr title="January 14, 2012 at 3:15 pm">January 14, 2012</abbr> &middot; by <a href="http://www.jamedy.com/author/admin/" title="Posts by admin" rel="author">admin</a>        </div><!-- .entry-meta -->        
        <div class="entry-content">
            <p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam molestie molestie nisl, eu scelerisque turpis tempus at. Nam luctus ultrices imperdiet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse velit orci, pretium ut feugiat nec, lobortis et est. Nullam cursus ultrices tincidunt. Nam gravida sem gravida ipsum dignissim in [&hellip;]</p>
</p>
            <a href="http://www.jamedy.com/2012/01/14/lady-vol-basketball-vs-texas/" rel="bookmark" class="read-more">Continue Reading &raquo;</a>
	    </div><!-- .entry-content -->
</div><!-- #post-68 -->
			    			    	<div class="entry-slides">
    <div class="entry-embed">
        <iframe width="560" height="315" src="http://www.youtube.com/embed/LMn8CK6uh_Y" frameborder="0" allowfullscreen></iframe>    </div>
	    <h2 class="entry-title">
            <a href="http://www.jamedy.com/2012/01/14/chase-armitage-2011-student-of-movement/" rel="bookmark" title="Permanent Link to Chase Armitage 2011 (Student Of Movement)">
                Chase Armitage 2011 (Student Of Movement)            </a>
        </h2><!-- .entry-title -->
        <div class="entry-meta">
            <abbr title="January 14, 2012 at 3:03 pm">January 14, 2012</abbr> &middot; by <a href="http://www.jamedy.com/author/admin/" title="Posts by admin" rel="author">admin</a>        </div><!-- .entry-meta -->        
        <div class="entry-content">
            <p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam molestie molestie nisl, eu scelerisque turpis tempus at. Nam luctus ultrices imperdiet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse velit orci, pretium ut feugiat nec, lobortis et est. Nullam cursus ultrices tincidunt. Nam gravida sem gravida ipsum dignissim in [&hellip;]</p>
</p>
            <a href="http://www.jamedy.com/2012/01/14/chase-armitage-2011-student-of-movement/" rel="bookmark" class="read-more">Continue Reading &raquo;</a>
	    </div><!-- .entry-content -->
</div><!-- #post-72 -->
			    			    	<div class="entry-slides">
    <div class="entry-embed">
        <iframe width="560" height="315" src="http://www.youtube.com/embed/ZBpOYnP72RU" frameborder="0" allowfullscreen></iframe>    </div>
	    <h2 class="entry-title">
            <a href="http://www.jamedy.com/2012/01/14/scishow-preview/" rel="bookmark" title="Permanent Link to SciShow Preview">
                SciShow Preview            </a>
        </h2><!-- .entry-title -->
        <div class="entry-meta">
            <abbr title="January 14, 2012 at 2:58 pm">January 14, 2012</abbr> &middot; by <a href="http://www.jamedy.com/author/admin/" title="Posts by admin" rel="author">admin</a>        </div><!-- .entry-meta -->        
        <div class="entry-content">
            <p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam molestie molestie nisl, eu scelerisque turpis tempus at. Nam luctus ultrices imperdiet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse velit orci, pretium ut feugiat nec, lobortis et est. Nullam cursus ultrices tincidunt. Nam gravida sem gravida ipsum dignissim in [&hellip;]</p>
</p>
            <a href="http://www.jamedy.com/2012/01/14/scishow-preview/" rel="bookmark" class="read-more">Continue Reading &raquo;</a>
	    </div><!-- .entry-content -->
</div><!-- #post-64 -->
			    			    	<div class="entry-slides">
    <div class="entry-embed">
        <object style="height: 390px; width: 640px"><param name="movie" value="http://www.youtube.com/v/SCJ24V9pF2E?version=3&feature=player_detailpage"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><embed src="http://www.youtube.com/v/SCJ24V9pF2E?version=3&feature=player_detailpage" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="640" height="360"></object>    </div>
	    <h2 class="entry-title">
            <a href="http://www.jamedy.com/2012/01/14/family-leader-executives-endorse-rick-santorum/" rel="bookmark" title="Permanent Link to Family Leader executives endorse Rick Santorum">
                Family Leader executives endorse Rick Santorum            </a>
        </h2><!-- .entry-title -->
        <div class="entry-meta">
            <abbr title="January 14, 2012 at 2:35 pm">January 14, 2012</abbr> &middot; by <a href="http://www.jamedy.com/author/admin/" title="Posts by admin" rel="author">admin</a>        </div><!-- .entry-meta -->        
        <div class="entry-content">
            <p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam molestie molestie nisl, eu scelerisque turpis tempus at. Nam luctus ultrices imperdiet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse velit orci, pretium ut feugiat nec, lobortis et est. Nullam cursus ultrices tincidunt. Nam gravida sem gravida ipsum dignissim in [&hellip;]</p>
</p>
            <a href="http://www.jamedy.com/2012/01/14/family-leader-executives-endorse-rick-santorum/" rel="bookmark" class="read-more">Continue Reading &raquo;</a>
	    </div><!-- .entry-content -->
</div><!-- #post-48 -->
			    			    	<div class="entry-slides">
    <div class="entry-embed">
        <object style="height: 390px; width: 540px"><param name="movie" value="http://www.youtube.com/v/ARxfNM3vBrI?version=3&feature=player_detailpage"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><embed src="http://www.youtube.com/v/ARxfNM3vBrI?version=3&feature=player_detailpage" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="540" height="360"></object>    </div>
	    <h2 class="entry-title">
            <a href="http://www.jamedy.com/2012/01/14/the-woman-with-two-vaginas/" rel="bookmark" title="Permanent Link to The Woman with Two Vaginas!">
                The Woman with Two Vaginas!            </a>
        </h2><!-- .entry-title -->
        <div class="entry-meta">
            <abbr title="January 14, 2012 at 2:30 pm">January 14, 2012</abbr> &middot; by <a href="http://www.jamedy.com/author/admin/" title="Posts by admin" rel="author">admin</a>        </div><!-- .entry-meta -->        
        <div class="entry-content">
            <p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam molestie molestie nisl, eu scelerisque turpis tempus at. Nam luctus ultrices imperdiet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse velit orci, pretium ut feugiat nec, lobortis et est. Nullam cursus ultrices tincidunt. Nam gravida sem gravida ipsum dignissim in [&hellip;]</p>
</p>
            <a href="http://www.jamedy.com/2012/01/14/the-woman-with-two-vaginas/" rel="bookmark" class="read-more">Continue Reading &raquo;</a>
	    </div><!-- .entry-content -->
</div><!-- #post-43 -->
			    			    	<div class="entry-slides">
    <div class="entry-embed">
        <object style="height: 390px; width: 640px"><param name="movie" value="http://www.youtube.com/v/tyFaWhygzjQ?version=3&feature=player_detailpage"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><embed src="http://www.youtube.com/v/tyFaWhygzjQ?version=3&feature=player_detailpage" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="640" height="360"></object>    </div>
	    <h2 class="entry-title">
            <a href="http://www.jamedy.com/2012/01/14/the-french-connection/" rel="bookmark" title="Permanent Link to The French Connection">
                The French Connection            </a>
        </h2><!-- .entry-title -->
        <div class="entry-meta">
            <abbr title="January 14, 2012 at 2:26 pm">January 14, 2012</abbr> &middot; by <a href="http://www.jamedy.com/author/admin/" title="Posts by admin" rel="author">admin</a>        </div><!-- .entry-meta -->        
        <div class="entry-content">
            <p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam molestie molestie nisl, eu scelerisque turpis tempus at. Nam luctus ultrices imperdiet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse velit orci, pretium ut feugiat nec, lobortis et est. Nullam cursus ultrices tincidunt. Nam gravida sem gravida ipsum dignissim in [&hellip;]</p>
</p>
            <a href="http://www.jamedy.com/2012/01/14/the-french-connection/" rel="bookmark" class="read-more">Continue Reading &raquo;</a>
	    </div><!-- .entry-content -->
</div><!-- #post-38 -->
			    			    	<div class="entry-slides">
    <div class="entry-embed">
        <iframe width="560" height="315" src="http://www.youtube.com/embed/BLWnB9FGmWE" frameborder="0" allowfullscreen></iframe>    </div>
	    <h2 class="entry-title">
            <a href="http://www.jamedy.com/2012/01/14/mayor-nutter-to-city-dont-act-like-idiots-and-assholes/" rel="bookmark" title="Permanent Link to When Mitt Romney Came To Town — Full, complete version">
                When Mitt Romney Came To Town — Full, complete version            </a>
        </h2><!-- .entry-title -->
        <div class="entry-meta">
            <abbr title="January 14, 2012 at 2:21 pm">January 14, 2012</abbr> &middot; by <a href="http://www.jamedy.com/author/admin/" title="Posts by admin" rel="author">admin</a>        </div><!-- .entry-meta -->        
        <div class="entry-content">
            <p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam molestie molestie nisl, eu scelerisque turpis tempus at. Nam luctus ultrices imperdiet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse velit orci, pretium ut feugiat nec, lobortis et est. Nullam cursus ultrices tincidunt. Nam gravida sem gravida ipsum dignissim in [&hellip;]</p>
</p>
            <a href="http://www.jamedy.com/2012/01/14/mayor-nutter-to-city-dont-act-like-idiots-and-assholes/" rel="bookmark" class="read-more">Continue Reading &raquo;</a>
	    </div><!-- .entry-content -->
</div><!-- #post-35 -->
</div><!-- .slides_container -->
<div id="slider-pagination">
<ul class="slider-nav">
<li>
<a rel="slider_title" title="The Artists" >
<img width="109" height="72" src="http://demo.theme-junkie.com/videoplus/files/2012/01/20-109x72.jpg" class="entry-thumb wp-post-image" alt="20" />
</a>
</li>
<li>
<a rel="slider_title" title="Lady Vol Basketball vs. Texas" ><img width="109" height="72" src="http://demo.theme-junkie.com/videoplus/files/2012/01/12-109x72.jpg" class="entry-thumb wp-post-image" alt="12" /></a>
</li>
<li>
<a rel="slider_title" title="Chase Armitage 2011 (Student Of Movement)" ><img width="109" height="72" src="http://demo.theme-junkie.com/videoplus/files/2012/01/9-109x72.jpg" class="entry-thumb wp-post-image" alt="9" /></a>
</li>
<li>
<a rel="slider_title" title="SciShow Preview" ><img width="109" height="72" src="http://demo.theme-junkie.com/videoplus/files/2012/01/7-109x72.jpg" class="entry-thumb wp-post-image" alt="7" /></a>
</li>
<li>
<a rel="slider_title" title="Family Leader executives endorse Rick Santorum" ><img width="109" height="72" src="http://demo.theme-junkie.com/videoplus/files/2012/01/5-109x72.jpg" class="entry-thumb wp-post-image" alt="5" /></a>
</li>
<li>
<a rel="slider_title" title="The Woman with Two Vaginas!" ><img width="109" height="72" src="http://demo.theme-junkie.com/videoplus/files/2012/01/4-109x72.jpg" class="entry-thumb wp-post-image" alt="4" /></a>
</li>
<li>
<a rel="slider_title" title="The French Connection" ><img width="109" height="72" src="http://demo.theme-junkie.com/videoplus/files/2012/01/2-109x72.jpg" class="entry-thumb wp-post-image" alt="2" /></a>
</li>
<li>
<a rel="slider_title" title="When Mitt Romney Came To Town — Full, complete version" > <img width="109" height="72" src="http://demo.theme-junkie.com/videoplus/files/2012/01/1-109x72.jpg" class="entry-thumb wp-post-image" alt="1" /></a
</li>
</ul>		 
</div><!-- #slider-pagination -->
<a class="prev" title="prev">prev</a>
<a class="next" title="next">next</a>
</div><!-- .wrap -->
</div><!-- #slider -->