<div id="video-123456" class="entry-box">
  <a href="http://www.jamedy.com/watch/123456" rel="bookmark" class="various fancybox.iframe">
    <img width="216" height="120" src="http://demo.theme-junkie.com/videoplus/files/2012/01/17.jpeg" class="entry-thumb wp-post-image" alt="17" />        
	<div class="video-flag"></div>
  </a>
  <div class="entry-meta">
    2 days ago        
    <span class="entry-comment">
      200,356        
    </span>
  </div><!-- .entry-meta -->
  <h2 class="entry-title"><a href="http://www.jamedy.com/watch/123456" title="The title of the video.">The title of the video.</a></h2>
</div><!-- .entry-box -->