<div id="bands" class="widget widget_recent_comments">
  <h3 class="widget-title"><span>Bands</span></h3>
  <div class="widget-content">
    <ul id="recentcomments">
      <li class="recentcomments">admin on <a href="http://www.jamedy.com/2012/01/14/reiver-baseball-grand-junction-challenge-ice-baths/#comment-8">Reiver Baseball Grand Junction Challenge &#8211; ICE BATHS!</a></li>
      <li class="recentcomments">admin on <a href="http://www.jamedy.com/2012/01/15/sample-post-with-image/#comment-7">Sample Post With Image</a></li>
      <li class="recentcomments">admin on <a href="http://www.jamedy.com/2012/01/15/sample-video-post-vimeo/#comment-6">Sample Video Post (Vimeo)</a></li>
    </ul>
  </div>
</div>