<?= $this->render('elements/slider.phtml');?>	    
<div class="wrap">	
  <div id="content">		
    <?= $this->render('elements/sectionbar.phtml');?>    		    
	    <article id="most-recent">
	   	  
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>

	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>    			    	

        </article><!-- article -->
        <div class="clear"></div>
		<div class="clear"></div>		
  </div><!-- #content -->
  <div id="sidebar">

    <?= $this->render('elements/sidebar/programs.phtml');?>
    <?= $this->render('elements/sidebar/bands.phtml');?>
  
  </div><!-- #sidebar -->
</div><!-- #wrap-->
<div class="clear"></div>
	        
		
		