<div class="entry-content">
  <div class="entry-embed">
	<object style="height: 350px; width: 600px">
	  <param name="movie" value="http://www.youtube.com/v/ezMdddYcRsc?version=3&feature=player_detailpage">
      <param name="allowFullScreen" value="true">
      <param name="allowScriptAccess" value="always">
      <embed src="http://www.youtube.com/v/ezMdddYcRsc?version=3&feature=player_detailpage" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="600" height="350">
    </object>
  </div><!-- .entry-embed -->		    	        
  <div class="clear"></div>
</div><!-- .entry-content -->
<div class="clear"></div>
<div class="entry-author-box clear">
  <div class="author-avatar"><img alt='' src='http://1.gravatar.com/avatar/7469a3bfa62f7504151166ffad29134c?s=60&amp;d=http%3A%2F%2F1.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D60&amp;r=G' class='avatar avatar-60 photo' height='60' width='60' /></div> <!-- .author-avatar -->
  <div class="author-description">
    <h3>admin</h3>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat volutpat nibh nec posuere.  Follow me 
    <a href="http://twitter.com/theme_junkie">@theme_junkie</a>
  </div> <!-- .author-description -->
  <div id="author-link">
    <a href="www.jamedy.com/author/admin/" title="View all posts by admin">View all posts by admin &rarr;</a>
  </div> <!-- .author-link -->
</div><!-- .entry-author-box -->