<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US">
  <head profile="http://gmpg.org/xfn/11">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Jamedy | Discover Music</title>
    <link rel="profile" href="http://gmpg.org/xfn/11" />
	<link rel="stylesheet" type="text/css" media="all" href="css/style.css" />
	<link rel="stylesheet" type="text/css" href="css/default.css" />
	<link rel="stylesheet" type="text/css" href="fancybox/jquery.fancybox.css" />
	<link rel="stylesheet" type="text/css" href="css/custom.css" />
	<link rel="stylesheet" id="wp-pagenavi-css"  href="css/pagenavi-css.css" type="text/css" media="all" />
	<script type='text/javascript' src='js/jquery.min.js'></script>
	<script type='text/javascript' src='js/shortcodes.js'></script>
	<script type='text/javascript' src='js/jquery-ui-1.8.5.custom.min.js'></script>
	<script type='text/javascript' src='js/superfish.js'></script>
	<script type='text/javascript' src='js/slides.min.jquery.js'></script>
	<script type='text/javascript' src='fancybox/jquery.fancybox.js'></script>
	<script type='text/javascript' src='js/custom.js'></script>
	<script type='text/javascript' src='js/html5.js'></script>
	
	<!-- Fav and Touch Icons -->
	<link rel="shortcut icon" href="img/favicon.png" /><!-- Custom Styling -->
<style type="text/css">
body { }
</style>
	<style type="text/css">.recentcomments a{display:inline !important;padding:0 !important;margin:0 !important;}</style>
</head>
<body class="home blog gecko">
	<span id="home-url" name="http://demo.theme-junkie.com/videoplus/wp-content/themes/videoplus" style="display: none;"></span>
	<header>
        <div class="wrap">
		    			    <a href="http://www.jamedy.com"><img src="img/logo.png" alt="VideoPlus" id="logo"/></a>
		    		    <div class="right">
			    <div id="primary-nav">
				    						<ul id="primary-navigation" class="nav">
							<li class="page_item page-item-7"><a href="http://www.jamedy.com/about/">About</a></li>
<li class="page_item page-item-9"><a href="http://www.jamedy.com/elements/">Elements</a></li>
<li class="page_item page-item-11 page_item_has_children"><a href="http://www.jamedy.com/page-templates/">Page Templates</a>
<ul class='children'>
	<li class="page_item page-item-13"><a href="http://www.jamedy.com/page-templates/archives/">Archives</a></li>
	<li class="page_item page-item-15"><a href="http://www.jamedy.com/page-templates/contact-form/">Contact Form</a></li>
	<li class="page_item page-item-22"><a href="http://www.jamedy.com/page-templates/full-width/">Full Width</a></li>
	<li class="page_item page-item-27"><a href="http://www.jamedy.com/page-templates/redirect/">Redirect</a></li>
	<li class="page_item page-item-24"><a href="http://www.jamedy.com/page-templates/sitemap/">Sitemap</a></li>
</ul>
</li>
<li class="page_item page-item-2"><a href="http://www.jamedy.com/shortcodes/">Shortcodes</a></li>
							<li class="top-twitter"><a href="http://twitter.com/theme_junkie">Follow us</a></li>								
							<li class="top-rss"><a href="http://feeds.feedburner.com/ThemeJunkie">RSS</a></li>				
						</ul>
									</div><!-- #primary-nav -->
				<div class="clear"></div>
				<div id="header-search" role="search">
					<form action="http://demo.theme-junkie.com/videoplus" method="get" id="search-form">
						<label><input type="text" name="s" id="site_search" value="Search this site..."  onfocus="if (this.value == 'Search this site...') {this.value = '';}" onblur="if (this.value == '') {this.value = 'Search this site...';}" /></label>
						<input type="submit" id="search-submit" value="Search" />
					</form>
				</div><!-- #header-search -->
			</div><!-- .right -->
		</div><!-- .wrap-->
    </header><!-- header-->
    
    <div class="clear"></div>
    
	<nav >
		<div class="wrap">
			<div id="secondary-nav">
							<ul id="secondary-navigation" class="nav">
											<li class="first"><a href="http://demo.theme-junkie.com/videoplus">Home</a></li>
											<li class="cat-item cat-item-1"><a href="http://www.jamedy.com/category/news/" title="View all posts filed under News">News</a>
<ul class='children'>
	<li class="cat-item cat-item-12"><a href="http://www.jamedy.com/category/news/sub-category-1/" title="View all posts filed under Sub Category 1">Sub Category 1</a>
</li>
	<li class="cat-item cat-item-14"><a href="http://www.jamedy.com/category/news/sub-category-2/" title="View all posts filed under Sub Category 2">Sub Category 2</a>
</li>
	<li class="cat-item cat-item-15"><a href="http://www.jamedy.com/category/news/sub-category-3/" title="View all posts filed under Sub Category 3">Sub Category 3</a>
</li>
</ul>
</li>
	<li class="cat-item cat-item-3"><a href="http://www.jamedy.com/category/animation/" title="View all posts filed under Animation">Animation</a>
</li>
	<li class="cat-item cat-item-4"><a href="http://www.jamedy.com/category/education/" title="View all posts filed under Education">Education</a>
</li>
	<li class="cat-item cat-item-5"><a href="http://www.jamedy.com/category/trailers/" title="View all posts filed under Trailers">Trailers</a>
<ul class='children'>
	<li class="cat-item cat-item-13"><a href="http://www.jamedy.com/category/trailers/sub-category-1-trialers/" title="View all posts filed under Sub Category 1">Sub Category 1</a>
	<ul class='children'>
	<li class="cat-item cat-item-18"><a href="http://www.jamedy.com/category/trailers/sub-category-1-trialers/sub-category-1-1/" title="View all posts filed under Sub Category 1.1">Sub Category 1.1</a>
</li>
	<li class="cat-item cat-item-19"><a href="http://www.jamedy.com/category/trailers/sub-category-1-trialers/sub-category-1-2/" title="View all posts filed under Sub Category 1.2">Sub Category 1.2</a>
</li>
	<li class="cat-item cat-item-20"><a href="http://www.jamedy.com/category/trailers/sub-category-1-trialers/sub-category-1-3/" title="View all posts filed under Sub Category 1.3">Sub Category 1.3</a>
</li>
	</ul>
</li>
	<li class="cat-item cat-item-16"><a href="http://www.jamedy.com/category/trailers/sub-category-2-trialers/" title="View all posts filed under Sub Category 2">Sub Category 2</a>
</li>
	<li class="cat-item cat-item-17"><a href="http://www.jamedy.com/category/trailers/sub-category-3-trialers/" title="View all posts filed under Sub Category 3">Sub Category 3</a>
</li>
</ul>
</li>
	<li class="cat-item cat-item-6"><a href="http://www.jamedy.com/category/nature/" title="View all posts filed under Nature">Nature</a>
</li>
	<li class="cat-item cat-item-7"><a href="http://www.jamedy.com/category/music/" title="View all posts filed under Music">Music</a>
</li>
	<li class="cat-item cat-item-8"><a href="http://www.jamedy.com/category/sports/" title="View all posts filed under Sports">Sports</a>
</li>
	<li class="cat-item cat-item-9"><a href="http://www.jamedy.com/category/travel/" title="View all posts filed under Travel">Travel</a>
</li>
	<li class="cat-item cat-item-10"><a href="http://www.jamedy.com/category/films/" title="View all posts filed under Films">Films</a>
</li>
	<li class="cat-item cat-item-11"><a href="http://www.jamedy.com/category/events/" title="View all posts filed under Events">Events</a>
</li>
				</ul>

						</div><!-- #secondary-nav -->
		</div><!-- .wrap -->
	</nav><!-- nav -->
				
<?php echo $this->layout()->content; ?>

<footer>			
				<div id="footer-widget-1">
					<div id="meta-3" class="widget footer-widget widget_meta"><h3 class="widget-title">Meta</h3>			<ul>
						<li><a href="http://www.jamedy.com/wp-login.php">Log in</a></li>
			<li><a href="http://www.jamedy.com/feed/" title="Syndicate this site using RSS 2.0">Entries <abbr title="Really Simple Syndication">RSS</abbr></a></li>
			<li><a href="http://www.jamedy.com/comments/feed/" title="The latest comments to all posts in RSS">Comments <abbr title="Really Simple Syndication">RSS</abbr></a></li>
			<li><a href="http://wordpress.org/" title="Powered by WordPress, state-of-the-art semantic personal publishing platform.">WordPress.org</a></li>						</ul>
</div>				</div>
		
				<div id="footer-widget-2">
					<div id="meta-4" class="widget footer-widget widget_meta"><h3 class="widget-title">Meta</h3>			<ul>
						<li><a href="http://www.jamedy.com/wp-login.php">Log in</a></li>
			<li><a href="http://www.jamedy.com/feed/" title="Syndicate this site using RSS 2.0">Entries <abbr title="Really Simple Syndication">RSS</abbr></a></li>
			<li><a href="http://www.jamedy.com/comments/feed/" title="The latest comments to all posts in RSS">Comments <abbr title="Really Simple Syndication">RSS</abbr></a></li>
			<li><a href="http://wordpress.org/" title="Powered by WordPress, state-of-the-art semantic personal publishing platform.">WordPress.org</a></li>						</ul>
</div>				</div>
				
				<div id="footer-widget-3">
					<div id="meta-5" class="widget footer-widget widget_meta"><h3 class="widget-title">Meta</h3>			<ul>
						<li><a href="http://www.jamedy.com/wp-login.php">Log in</a></li>
			<li><a href="http://www.jamedy.com/feed/" title="Syndicate this site using RSS 2.0">Entries <abbr title="Really Simple Syndication">RSS</abbr></a></li>
			<li><a href="http://www.jamedy.com/comments/feed/" title="The latest comments to all posts in RSS">Comments <abbr title="Really Simple Syndication">RSS</abbr></a></li>
			<li><a href="http://wordpress.org/" title="Powered by WordPress, state-of-the-art semantic personal publishing platform.">WordPress.org</a></li>						</ul>
</div>				</div>
			
				<div id="footer-widget-4">				
					<div id="meta-6" class="widget footer-widget widget_meta"><h3 class="widget-title">Meta</h3>			<ul>
						<li><a href="http://www.jamedy.com/wp-login.php">Log in</a></li>
			<li><a href="http://www.jamedy.com/feed/" title="Syndicate this site using RSS 2.0">Entries <abbr title="Really Simple Syndication">RSS</abbr></a></li>
			<li><a href="http://www.jamedy.com/comments/feed/" title="The latest comments to all posts in RSS">Comments <abbr title="Really Simple Syndication">RSS</abbr></a></li>
			<li><a href="http://wordpress.org/" title="Powered by WordPress, state-of-the-art semantic personal publishing platform.">WordPress.org</a></li>						</ul>
</div>				</div>
		
				<div class="clear"></div>
					
		</footer><!-- #footer -->
			
		
	<div class="copyright">
		
		<div class="left">
			Copyright &copy; 2014 <a href="http://demo.theme-junkie.com/videoplus" title="Just another Theme Junkie Demos site" rel="home">VideoPlus</a>. All rights reserved.
		</div><!-- .left -->
		
		<div class="right">
			<a href="http://www.theme-junkie.com">WordPress Video Theme</a> designed by <a href="http://www.theme-junkie.com">Theme Junkie</a>		</div><!-- .right -->
		    
		<div class="clear"></div>
		        
	</div><!-- .copyright -->
</body>
</html>

