<div class="wrap">	
  <div id="content">		
    <?= $this->render('elements/sectionbar.phtml');?>    		    
	    <article id="browse-results">
	   	  
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>

	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>
	   	  <?= $this->render('elements/videocard.phtml');?>   			    	

        </article><!-- article -->
        <div class="clear"></div>
		<div class="clear"></div>
		<?= $this->render('elements/pagination.phtml');?>		
  </div><!-- #content -->
</div><!-- #wrap-->
<div class="clear"></div>